services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: bankme-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/database.sqlite
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    networks:
      - bankme-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:8-alpine
    container_name: bankme-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bankme-network
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
    driver: local

networks:
  bankme-network:
    driver: bridge 