apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankme-backend
  namespace: default
  labels:
    app: bankme-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankme-backend
  template:
    metadata:
      labels:
        app: bankme-backend
    spec:
      containers:
      - name: bankme-backend
        image: REGION-docker.pkg.dev/PROJECT_ID/ARTIFACT_REGISTRY/bankme-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: bankme-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: bankme-secrets
              key: jwt-secret
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: bankme-secrets
              key: redis-url
        - name: NODE_ENV
          value: "production"
        - name: ALLOWED_ORIGINS
          value: "http://localhost:3000"
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /health
          port: 3001
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /health
          port: 3001
        initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bankme-backend-service
  namespace: default
  labels:
    app: bankme-backend
spec:
  selector:
    app: bankme-backend
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: bankme-secrets
  namespace: default
type: Opaque
data:
  # These values should be base64 encoded
  database-url: "ZmlsZTouL2Rldi5kYg=="
  jwt-secret: "YjRua20z"
  redis-url: "cmVkaXM6Ly8xMjcuMC4wLjE6NjM3OQ=="